// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.ovh.outputs.GetOrderCartProductResultPrice;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetOrderCartProductResult {
    /**
     * @return Product offer identifier
     * 
     */
    private String planCode;
    /**
     * @return Prices of the product offer
     * 
     */
    private List<GetOrderCartProductResultPrice> prices;
    /**
     * @return Name of the product
     * 
     */
    private String productName;
    /**
     * @return Product type
     * 
     */
    private String productType;

    private GetOrderCartProductResult() {}
    /**
     * @return Product offer identifier
     * 
     */
    public String planCode() {
        return this.planCode;
    }
    /**
     * @return Prices of the product offer
     * 
     */
    public List<GetOrderCartProductResultPrice> prices() {
        return this.prices;
    }
    /**
     * @return Name of the product
     * 
     */
    public String productName() {
        return this.productName;
    }
    /**
     * @return Product type
     * 
     */
    public String productType() {
        return this.productType;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetOrderCartProductResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String planCode;
        private List<GetOrderCartProductResultPrice> prices;
        private String productName;
        private String productType;
        public Builder() {}
        public Builder(GetOrderCartProductResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.planCode = defaults.planCode;
    	      this.prices = defaults.prices;
    	      this.productName = defaults.productName;
    	      this.productType = defaults.productType;
        }

        @CustomType.Setter
        public Builder planCode(String planCode) {
            this.planCode = Objects.requireNonNull(planCode);
            return this;
        }
        @CustomType.Setter
        public Builder prices(List<GetOrderCartProductResultPrice> prices) {
            this.prices = Objects.requireNonNull(prices);
            return this;
        }
        public Builder prices(GetOrderCartProductResultPrice... prices) {
            return prices(List.of(prices));
        }
        @CustomType.Setter
        public Builder productName(String productName) {
            this.productName = Objects.requireNonNull(productName);
            return this;
        }
        @CustomType.Setter
        public Builder productType(String productType) {
            this.productType = Objects.requireNonNull(productType);
            return this;
        }
        public GetOrderCartProductResult build() {
            final var o = new GetOrderCartProductResult();
            o.planCode = planCode;
            o.prices = prices;
            o.productName = productName;
            o.productType = productType;
            return o;
        }
    }
}
