// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IpLoadBalancingTcpRouteAction {
    /**
     * @return Farm ID for &#34;farm&#34; action type, empty for others.
     * 
     */
    private @Nullable String target;
    /**
     * @return Action to trigger if all the rules of this route matches
     * 
     */
    private String type;

    private IpLoadBalancingTcpRouteAction() {}
    /**
     * @return Farm ID for &#34;farm&#34; action type, empty for others.
     * 
     */
    public Optional<String> target() {
        return Optional.ofNullable(this.target);
    }
    /**
     * @return Action to trigger if all the rules of this route matches
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IpLoadBalancingTcpRouteAction defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String target;
        private String type;
        public Builder() {}
        public Builder(IpLoadBalancingTcpRouteAction defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.target = defaults.target;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder target(@Nullable String target) {
            this.target = target;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            this.type = Objects.requireNonNull(type);
            return this;
        }
        public IpLoadBalancingTcpRouteAction build() {
            final var o = new IpLoadBalancingTcpRouteAction();
            o.target = target;
            o.type = type;
            return o;
        }
    }
}
