// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.ovh.CloudProjectContainerRegistryArgs;
import com.pulumi.ovh.Utilities;
import com.pulumi.ovh.inputs.CloudProjectContainerRegistryState;
import com.pulumi.ovh.outputs.CloudProjectContainerRegistryPlan;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * Creates a container registry associated with a public cloud project.
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.ovh.OvhFunctions;
 * import com.pulumi.ovh.inputs.GetCloudProjectCapabilitiesContainerFilterArgs;
 * import com.pulumi.ovh.CloudProjectContainerRegistry;
 * import com.pulumi.ovh.CloudProjectContainerRegistryArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         final var regcap = OvhFunctions.getCloudProjectCapabilitiesContainerFilter(GetCloudProjectCapabilitiesContainerFilterArgs.builder()
 *             .serviceName(&#34;XXXXXX&#34;)
 *             .planName(&#34;SMALL&#34;)
 *             .region(&#34;GRA&#34;)
 *             .build());
 * 
 *         var reg = new CloudProjectContainerRegistry(&#34;reg&#34;, CloudProjectContainerRegistryArgs.builder()        
 *             .serviceName(regcap.applyValue(getCloudProjectCapabilitiesContainerFilterResult -&gt; getCloudProjectCapabilitiesContainerFilterResult.serviceName()))
 *             .planId(regcap.applyValue(getCloudProjectCapabilitiesContainerFilterResult -&gt; getCloudProjectCapabilitiesContainerFilterResult.id()))
 *             .region(regcap.applyValue(getCloudProjectCapabilitiesContainerFilterResult -&gt; getCloudProjectCapabilitiesContainerFilterResult.region()))
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="ovh:index/cloudProjectContainerRegistry:CloudProjectContainerRegistry")
public class CloudProjectContainerRegistry extends com.pulumi.resources.CustomResource {
    /**
     * Plan creation date
     * 
     */
    @Export(name="createdAt", type=String.class, parameters={})
    private Output<String> createdAt;

    /**
     * @return Plan creation date
     * 
     */
    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * Registry name
     * 
     */
    @Export(name="name", type=String.class, parameters={})
    private Output<String> name;

    /**
     * @return Registry name
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Plan ID of the registry
     * 
     */
    @Export(name="planId", type=String.class, parameters={})
    private Output<String> planId;

    /**
     * @return Plan ID of the registry
     * 
     */
    public Output<String> planId() {
        return this.planId;
    }
    /**
     * Plan of the registry
     * 
     */
    @Export(name="plans", type=List.class, parameters={CloudProjectContainerRegistryPlan.class})
    private Output<List<CloudProjectContainerRegistryPlan>> plans;

    /**
     * @return Plan of the registry
     * 
     */
    public Output<List<CloudProjectContainerRegistryPlan>> plans() {
        return this.plans;
    }
    /**
     * Project ID of your registry
     * 
     */
    @Export(name="projectId", type=String.class, parameters={})
    private Output<String> projectId;

    /**
     * @return Project ID of your registry
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }
    /**
     * Region of the registry
     * 
     */
    @Export(name="region", type=String.class, parameters={})
    private Output<String> region;

    /**
     * @return Region of the registry
     * 
     */
    public Output<String> region() {
        return this.region;
    }
    /**
     * The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     * 
     */
    @Export(name="serviceName", type=String.class, parameters={})
    private Output<String> serviceName;

    /**
     * @return The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     * 
     */
    public Output<String> serviceName() {
        return this.serviceName;
    }
    /**
     * Current size of the registry (bytes)
     * 
     */
    @Export(name="size", type=Integer.class, parameters={})
    private Output<Integer> size;

    /**
     * @return Current size of the registry (bytes)
     * 
     */
    public Output<Integer> size() {
        return this.size;
    }
    /**
     * Registry status
     * 
     */
    @Export(name="status", type=String.class, parameters={})
    private Output<String> status;

    /**
     * @return Registry status
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Registry last update date
     * 
     */
    @Export(name="updatedAt", type=String.class, parameters={})
    private Output<String> updatedAt;

    /**
     * @return Registry last update date
     * 
     */
    public Output<String> updatedAt() {
        return this.updatedAt;
    }
    /**
     * Access url of the registry
     * 
     */
    @Export(name="url", type=String.class, parameters={})
    private Output<String> url;

    /**
     * @return Access url of the registry
     * 
     */
    public Output<String> url() {
        return this.url;
    }
    /**
     * Version of your registry
     * 
     */
    @Export(name="version", type=String.class, parameters={})
    private Output<String> version;

    /**
     * @return Version of your registry
     * 
     */
    public Output<String> version() {
        return this.version;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public CloudProjectContainerRegistry(String name) {
        this(name, CloudProjectContainerRegistryArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public CloudProjectContainerRegistry(String name, CloudProjectContainerRegistryArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public CloudProjectContainerRegistry(String name, CloudProjectContainerRegistryArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ovh:index/cloudProjectContainerRegistry:CloudProjectContainerRegistry", name, args == null ? CloudProjectContainerRegistryArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private CloudProjectContainerRegistry(String name, Output<String> id, @Nullable CloudProjectContainerRegistryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ovh:index/cloudProjectContainerRegistry:CloudProjectContainerRegistry", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static CloudProjectContainerRegistry get(String name, Output<String> id, @Nullable CloudProjectContainerRegistryState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new CloudProjectContainerRegistry(name, id, state, options);
    }
}
