// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.ovh.DedicatedServiceInstallTaskArgs;
import com.pulumi.ovh.Utilities;
import com.pulumi.ovh.inputs.DedicatedServiceInstallTaskState;
import com.pulumi.ovh.outputs.DedicatedServiceInstallTaskDetails;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="ovh:index/dedicatedServiceInstallTask:DedicatedServiceInstallTask")
public class DedicatedServiceInstallTask extends com.pulumi.resources.CustomResource {
    /**
     * If set, reboot the server on the specified boot id during destroy phase.
     * 
     */
    @Export(name="bootidOnDestroy", type=Integer.class, parameters={})
    private Output</* @Nullable */ Integer> bootidOnDestroy;

    /**
     * @return If set, reboot the server on the specified boot id during destroy phase.
     * 
     */
    public Output<Optional<Integer>> bootidOnDestroy() {
        return Codegen.optional(this.bootidOnDestroy);
    }
    /**
     * Details of this task. (should be `Install asked`)
     * 
     */
    @Export(name="comment", type=String.class, parameters={})
    private Output<String> comment;

    /**
     * @return Details of this task. (should be `Install asked`)
     * 
     */
    public Output<String> comment() {
        return this.comment;
    }
    /**
     * see `details` block below.
     * 
     */
    @Export(name="details", type=DedicatedServiceInstallTaskDetails.class, parameters={})
    private Output</* @Nullable */ DedicatedServiceInstallTaskDetails> details;

    /**
     * @return see `details` block below.
     * 
     */
    public Output<Optional<DedicatedServiceInstallTaskDetails>> details() {
        return Codegen.optional(this.details);
    }
    /**
     * Completion date in RFC3339 format.
     * 
     */
    @Export(name="doneDate", type=String.class, parameters={})
    private Output<String> doneDate;

    /**
     * @return Completion date in RFC3339 format.
     * 
     */
    public Output<String> doneDate() {
        return this.doneDate;
    }
    /**
     * Function name (should be `hardInstall`).
     * 
     */
    @Export(name="function", type=String.class, parameters={})
    private Output<String> function;

    /**
     * @return Function name (should be `hardInstall`).
     * 
     */
    public Output<String> function() {
        return this.function;
    }
    /**
     * Last update in RFC3339 format.
     * 
     */
    @Export(name="lastUpdate", type=String.class, parameters={})
    private Output<String> lastUpdate;

    /**
     * @return Last update in RFC3339 format.
     * 
     */
    public Output<String> lastUpdate() {
        return this.lastUpdate;
    }
    /**
     * Partition scheme name.
     * 
     */
    @Export(name="partitionSchemeName", type=String.class, parameters={})
    private Output</* @Nullable */ String> partitionSchemeName;

    /**
     * @return Partition scheme name.
     * 
     */
    public Output<Optional<String>> partitionSchemeName() {
        return Codegen.optional(this.partitionSchemeName);
    }
    /**
     * The service_name of your dedicated server.
     * 
     */
    @Export(name="serviceName", type=String.class, parameters={})
    private Output<String> serviceName;

    /**
     * @return The service_name of your dedicated server.
     * 
     */
    public Output<String> serviceName() {
        return this.serviceName;
    }
    /**
     * Task creation date in RFC3339 format.
     * 
     */
    @Export(name="startDate", type=String.class, parameters={})
    private Output<String> startDate;

    /**
     * @return Task creation date in RFC3339 format.
     * 
     */
    public Output<String> startDate() {
        return this.startDate;
    }
    /**
     * Task status (should be `done`)
     * 
     */
    @Export(name="status", type=String.class, parameters={})
    private Output<String> status;

    /**
     * @return Task status (should be `done`)
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Template name.
     * 
     */
    @Export(name="templateName", type=String.class, parameters={})
    private Output<String> templateName;

    /**
     * @return Template name.
     * 
     */
    public Output<String> templateName() {
        return this.templateName;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DedicatedServiceInstallTask(String name) {
        this(name, DedicatedServiceInstallTaskArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DedicatedServiceInstallTask(String name, DedicatedServiceInstallTaskArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DedicatedServiceInstallTask(String name, DedicatedServiceInstallTaskArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ovh:index/dedicatedServiceInstallTask:DedicatedServiceInstallTask", name, args == null ? DedicatedServiceInstallTaskArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private DedicatedServiceInstallTask(String name, Output<String> id, @Nullable DedicatedServiceInstallTaskState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ovh:index/dedicatedServiceInstallTask:DedicatedServiceInstallTask", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DedicatedServiceInstallTask get(String name, Output<String> id, @Nullable DedicatedServiceInstallTaskState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DedicatedServiceInstallTask(name, id, state, options);
    }
}
