// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.ovh.IpLoadBalancingHttpRouteArgs;
import com.pulumi.ovh.Utilities;
import com.pulumi.ovh.inputs.IpLoadBalancingHttpRouteState;
import com.pulumi.ovh.outputs.IpLoadBalancingHttpRouteAction;
import com.pulumi.ovh.outputs.IpLoadBalancingHttpRouteRule;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manage http route for a loadbalancer service
 * 
 * ## Example Usage
 * 
 * Route which redirect all url to https.
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.ovh.IpLoadBalancingHttpRoute;
 * import com.pulumi.ovh.IpLoadBalancingHttpRouteArgs;
 * import com.pulumi.ovh.inputs.IpLoadBalancingHttpRouteActionArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var httpsredirect = new IpLoadBalancingHttpRoute(&#34;httpsredirect&#34;, IpLoadBalancingHttpRouteArgs.builder()        
 *             .action(IpLoadBalancingHttpRouteActionArgs.builder()
 *                 .status(302)
 *                 .target(String.format(&#34;https://%s%s%s&#34;, host,path,arguments))
 *                 .type(&#34;redirect&#34;)
 *                 .build())
 *             .displayName(&#34;Redirect to HTTPS&#34;)
 *             .serviceName(&#34;loadbalancer-xxxxxxxxxxxxxxxxxx&#34;)
 *             .weight(1)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="ovh:index/ipLoadBalancingHttpRoute:IpLoadBalancingHttpRoute")
public class IpLoadBalancingHttpRoute extends com.pulumi.resources.CustomResource {
    /**
     * Action triggered when all rules match
     * 
     */
    @Export(name="action", type=IpLoadBalancingHttpRouteAction.class, parameters={})
    private Output<IpLoadBalancingHttpRouteAction> action;

    /**
     * @return Action triggered when all rules match
     * 
     */
    public Output<IpLoadBalancingHttpRouteAction> action() {
        return this.action;
    }
    /**
     * Human readable name for your route, this field is for you
     * 
     */
    @Export(name="displayName", type=String.class, parameters={})
    private Output</* @Nullable */ String> displayName;

    /**
     * @return Human readable name for your route, this field is for you
     * 
     */
    public Output<Optional<String>> displayName() {
        return Codegen.optional(this.displayName);
    }
    /**
     * Route traffic for this frontend
     * 
     */
    @Export(name="frontendId", type=Integer.class, parameters={})
    private Output<Integer> frontendId;

    /**
     * @return Route traffic for this frontend
     * 
     */
    public Output<Integer> frontendId() {
        return this.frontendId;
    }
    /**
     * List of rules to match to trigger action
     * 
     */
    @Export(name="rules", type=List.class, parameters={IpLoadBalancingHttpRouteRule.class})
    private Output<List<IpLoadBalancingHttpRouteRule>> rules;

    /**
     * @return List of rules to match to trigger action
     * 
     */
    public Output<List<IpLoadBalancingHttpRouteRule>> rules() {
        return this.rules;
    }
    /**
     * The internal name of your IP load balancing
     * 
     */
    @Export(name="serviceName", type=String.class, parameters={})
    private Output<String> serviceName;

    /**
     * @return The internal name of your IP load balancing
     * 
     */
    public Output<String> serviceName() {
        return this.serviceName;
    }
    /**
     * HTTP status code for &#34;redirect&#34; and &#34;reject&#34; actions
     * 
     */
    @Export(name="status", type=String.class, parameters={})
    private Output<String> status;

    /**
     * @return HTTP status code for &#34;redirect&#34; and &#34;reject&#34; actions
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * Route priority ([0..255]). 0 if null. Highest priority routes are evaluated first. Only the first matching route will trigger an action
     * 
     */
    @Export(name="weight", type=Integer.class, parameters={})
    private Output<Integer> weight;

    /**
     * @return Route priority ([0..255]). 0 if null. Highest priority routes are evaluated first. Only the first matching route will trigger an action
     * 
     */
    public Output<Integer> weight() {
        return this.weight;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IpLoadBalancingHttpRoute(String name) {
        this(name, IpLoadBalancingHttpRouteArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IpLoadBalancingHttpRoute(String name, IpLoadBalancingHttpRouteArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IpLoadBalancingHttpRoute(String name, IpLoadBalancingHttpRouteArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ovh:index/ipLoadBalancingHttpRoute:IpLoadBalancingHttpRoute", name, args == null ? IpLoadBalancingHttpRouteArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private IpLoadBalancingHttpRoute(String name, Output<String> id, @Nullable IpLoadBalancingHttpRouteState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("ovh:index/ipLoadBalancingHttpRoute:IpLoadBalancingHttpRoute", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static IpLoadBalancingHttpRoute get(String name, Output<String> id, @Nullable IpLoadBalancingHttpRouteState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new IpLoadBalancingHttpRoute(name, id, state, options);
    }
}
