// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates a subnet in a private network of a public cloud project.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/pulumiverse/pulumi-ovh/sdk/go/ovh"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := ovh.NewCloudProjectNetworkPrivateSubnet(ctx, "subnet", &ovh.CloudProjectNetworkPrivateSubnetArgs{
//				Dhcp:        pulumi.Bool(true),
//				End:         pulumi.String("192.168.168.200"),
//				Network:     pulumi.String("192.168.168.0/24"),
//				NetworkId:   pulumi.String("0234543"),
//				NoGateway:   pulumi.Bool(false),
//				Region:      pulumi.String("GRA1"),
//				ServiceName: pulumi.String("xxxxx"),
//				Start:       pulumi.String("192.168.168.100"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type CloudProjectNetworkPrivateSubnet struct {
	pulumi.CustomResourceState

	// Ip Block representing the subnet cidr.
	Cidr pulumi.StringOutput `pulumi:"cidr"`
	// Enable DHCP.
	// Changing this forces a new resource to be created. Defaults to false.
	// _
	Dhcp pulumi.BoolPtrOutput `pulumi:"dhcp"`
	// Last ip for this region.
	// Changing this value recreates the subnet.
	End pulumi.StringOutput `pulumi:"end"`
	// The IP of the gateway
	GatewayIp pulumi.StringOutput `pulumi:"gatewayIp"`
	// List of ip pools allocated in the subnet.
	// * `ip_pools/network` - Global network with cidr.
	// * `ip_pools/region` - Region where this subnet is created.
	// * `ip_pools/dhcp` - DHCP enabled.
	// * `ip_pools/end` - Last ip for this region.
	// * `ip_pools/start` - First ip for this region.
	IpPools CloudProjectNetworkPrivateSubnetIpPoolArrayOutput `pulumi:"ipPools"`
	// Global network in CIDR format.
	// Changing this value recreates the subnet
	Network pulumi.StringOutput `pulumi:"network"`
	// The id of the network.
	// Changing this forces a new resource to be created.
	NetworkId pulumi.StringOutput `pulumi:"networkId"`
	// Set to true if you don't want to set a default gateway IP.
	// Changing this value recreates the resource. Defaults to false.
	NoGateway pulumi.BoolPtrOutput `pulumi:"noGateway"`
	// The region in which the network subnet will be created.
	// Ex.: "GRA1". Changing this value recreates the resource.
	Region pulumi.StringOutput `pulumi:"region"`
	// The id of the public cloud project. If omitted,
	// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName pulumi.StringOutput `pulumi:"serviceName"`
	// First ip for this region.
	// Changing this value recreates the subnet.
	Start pulumi.StringOutput `pulumi:"start"`
}

// NewCloudProjectNetworkPrivateSubnet registers a new resource with the given unique name, arguments, and options.
func NewCloudProjectNetworkPrivateSubnet(ctx *pulumi.Context,
	name string, args *CloudProjectNetworkPrivateSubnetArgs, opts ...pulumi.ResourceOption) (*CloudProjectNetworkPrivateSubnet, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.End == nil {
		return nil, errors.New("invalid value for required argument 'End'")
	}
	if args.Network == nil {
		return nil, errors.New("invalid value for required argument 'Network'")
	}
	if args.NetworkId == nil {
		return nil, errors.New("invalid value for required argument 'NetworkId'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.ServiceName == nil {
		return nil, errors.New("invalid value for required argument 'ServiceName'")
	}
	if args.Start == nil {
		return nil, errors.New("invalid value for required argument 'Start'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource CloudProjectNetworkPrivateSubnet
	err := ctx.RegisterResource("ovh:index/cloudProjectNetworkPrivateSubnet:CloudProjectNetworkPrivateSubnet", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudProjectNetworkPrivateSubnet gets an existing CloudProjectNetworkPrivateSubnet resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudProjectNetworkPrivateSubnet(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudProjectNetworkPrivateSubnetState, opts ...pulumi.ResourceOption) (*CloudProjectNetworkPrivateSubnet, error) {
	var resource CloudProjectNetworkPrivateSubnet
	err := ctx.ReadResource("ovh:index/cloudProjectNetworkPrivateSubnet:CloudProjectNetworkPrivateSubnet", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudProjectNetworkPrivateSubnet resources.
type cloudProjectNetworkPrivateSubnetState struct {
	// Ip Block representing the subnet cidr.
	Cidr *string `pulumi:"cidr"`
	// Enable DHCP.
	// Changing this forces a new resource to be created. Defaults to false.
	// _
	Dhcp *bool `pulumi:"dhcp"`
	// Last ip for this region.
	// Changing this value recreates the subnet.
	End *string `pulumi:"end"`
	// The IP of the gateway
	GatewayIp *string `pulumi:"gatewayIp"`
	// List of ip pools allocated in the subnet.
	// * `ip_pools/network` - Global network with cidr.
	// * `ip_pools/region` - Region where this subnet is created.
	// * `ip_pools/dhcp` - DHCP enabled.
	// * `ip_pools/end` - Last ip for this region.
	// * `ip_pools/start` - First ip for this region.
	IpPools []CloudProjectNetworkPrivateSubnetIpPool `pulumi:"ipPools"`
	// Global network in CIDR format.
	// Changing this value recreates the subnet
	Network *string `pulumi:"network"`
	// The id of the network.
	// Changing this forces a new resource to be created.
	NetworkId *string `pulumi:"networkId"`
	// Set to true if you don't want to set a default gateway IP.
	// Changing this value recreates the resource. Defaults to false.
	NoGateway *bool `pulumi:"noGateway"`
	// The region in which the network subnet will be created.
	// Ex.: "GRA1". Changing this value recreates the resource.
	Region *string `pulumi:"region"`
	// The id of the public cloud project. If omitted,
	// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName *string `pulumi:"serviceName"`
	// First ip for this region.
	// Changing this value recreates the subnet.
	Start *string `pulumi:"start"`
}

type CloudProjectNetworkPrivateSubnetState struct {
	// Ip Block representing the subnet cidr.
	Cidr pulumi.StringPtrInput
	// Enable DHCP.
	// Changing this forces a new resource to be created. Defaults to false.
	// _
	Dhcp pulumi.BoolPtrInput
	// Last ip for this region.
	// Changing this value recreates the subnet.
	End pulumi.StringPtrInput
	// The IP of the gateway
	GatewayIp pulumi.StringPtrInput
	// List of ip pools allocated in the subnet.
	// * `ip_pools/network` - Global network with cidr.
	// * `ip_pools/region` - Region where this subnet is created.
	// * `ip_pools/dhcp` - DHCP enabled.
	// * `ip_pools/end` - Last ip for this region.
	// * `ip_pools/start` - First ip for this region.
	IpPools CloudProjectNetworkPrivateSubnetIpPoolArrayInput
	// Global network in CIDR format.
	// Changing this value recreates the subnet
	Network pulumi.StringPtrInput
	// The id of the network.
	// Changing this forces a new resource to be created.
	NetworkId pulumi.StringPtrInput
	// Set to true if you don't want to set a default gateway IP.
	// Changing this value recreates the resource. Defaults to false.
	NoGateway pulumi.BoolPtrInput
	// The region in which the network subnet will be created.
	// Ex.: "GRA1". Changing this value recreates the resource.
	Region pulumi.StringPtrInput
	// The id of the public cloud project. If omitted,
	// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName pulumi.StringPtrInput
	// First ip for this region.
	// Changing this value recreates the subnet.
	Start pulumi.StringPtrInput
}

func (CloudProjectNetworkPrivateSubnetState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudProjectNetworkPrivateSubnetState)(nil)).Elem()
}

type cloudProjectNetworkPrivateSubnetArgs struct {
	// Enable DHCP.
	// Changing this forces a new resource to be created. Defaults to false.
	// _
	Dhcp *bool `pulumi:"dhcp"`
	// Last ip for this region.
	// Changing this value recreates the subnet.
	End string `pulumi:"end"`
	// Global network in CIDR format.
	// Changing this value recreates the subnet
	Network string `pulumi:"network"`
	// The id of the network.
	// Changing this forces a new resource to be created.
	NetworkId string `pulumi:"networkId"`
	// Set to true if you don't want to set a default gateway IP.
	// Changing this value recreates the resource. Defaults to false.
	NoGateway *bool `pulumi:"noGateway"`
	// The region in which the network subnet will be created.
	// Ex.: "GRA1". Changing this value recreates the resource.
	Region string `pulumi:"region"`
	// The id of the public cloud project. If omitted,
	// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName string `pulumi:"serviceName"`
	// First ip for this region.
	// Changing this value recreates the subnet.
	Start string `pulumi:"start"`
}

// The set of arguments for constructing a CloudProjectNetworkPrivateSubnet resource.
type CloudProjectNetworkPrivateSubnetArgs struct {
	// Enable DHCP.
	// Changing this forces a new resource to be created. Defaults to false.
	// _
	Dhcp pulumi.BoolPtrInput
	// Last ip for this region.
	// Changing this value recreates the subnet.
	End pulumi.StringInput
	// Global network in CIDR format.
	// Changing this value recreates the subnet
	Network pulumi.StringInput
	// The id of the network.
	// Changing this forces a new resource to be created.
	NetworkId pulumi.StringInput
	// Set to true if you don't want to set a default gateway IP.
	// Changing this value recreates the resource. Defaults to false.
	NoGateway pulumi.BoolPtrInput
	// The region in which the network subnet will be created.
	// Ex.: "GRA1". Changing this value recreates the resource.
	Region pulumi.StringInput
	// The id of the public cloud project. If omitted,
	// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName pulumi.StringInput
	// First ip for this region.
	// Changing this value recreates the subnet.
	Start pulumi.StringInput
}

func (CloudProjectNetworkPrivateSubnetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudProjectNetworkPrivateSubnetArgs)(nil)).Elem()
}

type CloudProjectNetworkPrivateSubnetInput interface {
	pulumi.Input

	ToCloudProjectNetworkPrivateSubnetOutput() CloudProjectNetworkPrivateSubnetOutput
	ToCloudProjectNetworkPrivateSubnetOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateSubnetOutput
}

func (*CloudProjectNetworkPrivateSubnet) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudProjectNetworkPrivateSubnet)(nil)).Elem()
}

func (i *CloudProjectNetworkPrivateSubnet) ToCloudProjectNetworkPrivateSubnetOutput() CloudProjectNetworkPrivateSubnetOutput {
	return i.ToCloudProjectNetworkPrivateSubnetOutputWithContext(context.Background())
}

func (i *CloudProjectNetworkPrivateSubnet) ToCloudProjectNetworkPrivateSubnetOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateSubnetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudProjectNetworkPrivateSubnetOutput)
}

// CloudProjectNetworkPrivateSubnetArrayInput is an input type that accepts CloudProjectNetworkPrivateSubnetArray and CloudProjectNetworkPrivateSubnetArrayOutput values.
// You can construct a concrete instance of `CloudProjectNetworkPrivateSubnetArrayInput` via:
//
//	CloudProjectNetworkPrivateSubnetArray{ CloudProjectNetworkPrivateSubnetArgs{...} }
type CloudProjectNetworkPrivateSubnetArrayInput interface {
	pulumi.Input

	ToCloudProjectNetworkPrivateSubnetArrayOutput() CloudProjectNetworkPrivateSubnetArrayOutput
	ToCloudProjectNetworkPrivateSubnetArrayOutputWithContext(context.Context) CloudProjectNetworkPrivateSubnetArrayOutput
}

type CloudProjectNetworkPrivateSubnetArray []CloudProjectNetworkPrivateSubnetInput

func (CloudProjectNetworkPrivateSubnetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudProjectNetworkPrivateSubnet)(nil)).Elem()
}

func (i CloudProjectNetworkPrivateSubnetArray) ToCloudProjectNetworkPrivateSubnetArrayOutput() CloudProjectNetworkPrivateSubnetArrayOutput {
	return i.ToCloudProjectNetworkPrivateSubnetArrayOutputWithContext(context.Background())
}

func (i CloudProjectNetworkPrivateSubnetArray) ToCloudProjectNetworkPrivateSubnetArrayOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateSubnetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudProjectNetworkPrivateSubnetArrayOutput)
}

// CloudProjectNetworkPrivateSubnetMapInput is an input type that accepts CloudProjectNetworkPrivateSubnetMap and CloudProjectNetworkPrivateSubnetMapOutput values.
// You can construct a concrete instance of `CloudProjectNetworkPrivateSubnetMapInput` via:
//
//	CloudProjectNetworkPrivateSubnetMap{ "key": CloudProjectNetworkPrivateSubnetArgs{...} }
type CloudProjectNetworkPrivateSubnetMapInput interface {
	pulumi.Input

	ToCloudProjectNetworkPrivateSubnetMapOutput() CloudProjectNetworkPrivateSubnetMapOutput
	ToCloudProjectNetworkPrivateSubnetMapOutputWithContext(context.Context) CloudProjectNetworkPrivateSubnetMapOutput
}

type CloudProjectNetworkPrivateSubnetMap map[string]CloudProjectNetworkPrivateSubnetInput

func (CloudProjectNetworkPrivateSubnetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudProjectNetworkPrivateSubnet)(nil)).Elem()
}

func (i CloudProjectNetworkPrivateSubnetMap) ToCloudProjectNetworkPrivateSubnetMapOutput() CloudProjectNetworkPrivateSubnetMapOutput {
	return i.ToCloudProjectNetworkPrivateSubnetMapOutputWithContext(context.Background())
}

func (i CloudProjectNetworkPrivateSubnetMap) ToCloudProjectNetworkPrivateSubnetMapOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateSubnetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudProjectNetworkPrivateSubnetMapOutput)
}

type CloudProjectNetworkPrivateSubnetOutput struct{ *pulumi.OutputState }

func (CloudProjectNetworkPrivateSubnetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudProjectNetworkPrivateSubnet)(nil)).Elem()
}

func (o CloudProjectNetworkPrivateSubnetOutput) ToCloudProjectNetworkPrivateSubnetOutput() CloudProjectNetworkPrivateSubnetOutput {
	return o
}

func (o CloudProjectNetworkPrivateSubnetOutput) ToCloudProjectNetworkPrivateSubnetOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateSubnetOutput {
	return o
}

// Ip Block representing the subnet cidr.
func (o CloudProjectNetworkPrivateSubnetOutput) Cidr() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.Cidr }).(pulumi.StringOutput)
}

// Enable DHCP.
// Changing this forces a new resource to be created. Defaults to false.
// _
func (o CloudProjectNetworkPrivateSubnetOutput) Dhcp() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.BoolPtrOutput { return v.Dhcp }).(pulumi.BoolPtrOutput)
}

// Last ip for this region.
// Changing this value recreates the subnet.
func (o CloudProjectNetworkPrivateSubnetOutput) End() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.End }).(pulumi.StringOutput)
}

// The IP of the gateway
func (o CloudProjectNetworkPrivateSubnetOutput) GatewayIp() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.GatewayIp }).(pulumi.StringOutput)
}

// List of ip pools allocated in the subnet.
// * `ip_pools/network` - Global network with cidr.
// * `ip_pools/region` - Region where this subnet is created.
// * `ip_pools/dhcp` - DHCP enabled.
// * `ip_pools/end` - Last ip for this region.
// * `ip_pools/start` - First ip for this region.
func (o CloudProjectNetworkPrivateSubnetOutput) IpPools() CloudProjectNetworkPrivateSubnetIpPoolArrayOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) CloudProjectNetworkPrivateSubnetIpPoolArrayOutput {
		return v.IpPools
	}).(CloudProjectNetworkPrivateSubnetIpPoolArrayOutput)
}

// Global network in CIDR format.
// Changing this value recreates the subnet
func (o CloudProjectNetworkPrivateSubnetOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.Network }).(pulumi.StringOutput)
}

// The id of the network.
// Changing this forces a new resource to be created.
func (o CloudProjectNetworkPrivateSubnetOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.NetworkId }).(pulumi.StringOutput)
}

// Set to true if you don't want to set a default gateway IP.
// Changing this value recreates the resource. Defaults to false.
func (o CloudProjectNetworkPrivateSubnetOutput) NoGateway() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.BoolPtrOutput { return v.NoGateway }).(pulumi.BoolPtrOutput)
}

// The region in which the network subnet will be created.
// Ex.: "GRA1". Changing this value recreates the resource.
func (o CloudProjectNetworkPrivateSubnetOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// The id of the public cloud project. If omitted,
// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
func (o CloudProjectNetworkPrivateSubnetOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.ServiceName }).(pulumi.StringOutput)
}

// First ip for this region.
// Changing this value recreates the subnet.
func (o CloudProjectNetworkPrivateSubnetOutput) Start() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudProjectNetworkPrivateSubnet) pulumi.StringOutput { return v.Start }).(pulumi.StringOutput)
}

type CloudProjectNetworkPrivateSubnetArrayOutput struct{ *pulumi.OutputState }

func (CloudProjectNetworkPrivateSubnetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudProjectNetworkPrivateSubnet)(nil)).Elem()
}

func (o CloudProjectNetworkPrivateSubnetArrayOutput) ToCloudProjectNetworkPrivateSubnetArrayOutput() CloudProjectNetworkPrivateSubnetArrayOutput {
	return o
}

func (o CloudProjectNetworkPrivateSubnetArrayOutput) ToCloudProjectNetworkPrivateSubnetArrayOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateSubnetArrayOutput {
	return o
}

func (o CloudProjectNetworkPrivateSubnetArrayOutput) Index(i pulumi.IntInput) CloudProjectNetworkPrivateSubnetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CloudProjectNetworkPrivateSubnet {
		return vs[0].([]*CloudProjectNetworkPrivateSubnet)[vs[1].(int)]
	}).(CloudProjectNetworkPrivateSubnetOutput)
}

type CloudProjectNetworkPrivateSubnetMapOutput struct{ *pulumi.OutputState }

func (CloudProjectNetworkPrivateSubnetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudProjectNetworkPrivateSubnet)(nil)).Elem()
}

func (o CloudProjectNetworkPrivateSubnetMapOutput) ToCloudProjectNetworkPrivateSubnetMapOutput() CloudProjectNetworkPrivateSubnetMapOutput {
	return o
}

func (o CloudProjectNetworkPrivateSubnetMapOutput) ToCloudProjectNetworkPrivateSubnetMapOutputWithContext(ctx context.Context) CloudProjectNetworkPrivateSubnetMapOutput {
	return o
}

func (o CloudProjectNetworkPrivateSubnetMapOutput) MapIndex(k pulumi.StringInput) CloudProjectNetworkPrivateSubnetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CloudProjectNetworkPrivateSubnet {
		return vs[0].(map[string]*CloudProjectNetworkPrivateSubnet)[vs[1].(string)]
	}).(CloudProjectNetworkPrivateSubnetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudProjectNetworkPrivateSubnetInput)(nil)).Elem(), &CloudProjectNetworkPrivateSubnet{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudProjectNetworkPrivateSubnetArrayInput)(nil)).Elem(), CloudProjectNetworkPrivateSubnetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudProjectNetworkPrivateSubnetMapInput)(nil)).Elem(), CloudProjectNetworkPrivateSubnetMap{})
	pulumi.RegisterOutputType(CloudProjectNetworkPrivateSubnetOutput{})
	pulumi.RegisterOutputType(CloudProjectNetworkPrivateSubnetArrayOutput{})
	pulumi.RegisterOutputType(CloudProjectNetworkPrivateSubnetMapOutput{})
}
