// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to get the list of users of a database cluster associated with a public cloud project.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbrlabs/pulumi-ovh/sdk/go/ovh"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			users, err := ovh.GetCloudProjectDatabaseUsers(ctx, &GetCloudProjectDatabaseUsersArgs{
//				ServiceName: "XXXX",
//				Engine:      "YYYY",
//				ClusterId:   "ZZZ",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("userIds", users.UserIds)
//			return nil
//		})
//	}
//
// ```
func GetCloudProjectDatabaseUsers(ctx *pulumi.Context, args *GetCloudProjectDatabaseUsersArgs, opts ...pulumi.InvokeOption) (*GetCloudProjectDatabaseUsersResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetCloudProjectDatabaseUsersResult
	err := ctx.Invoke("ovh:index/getCloudProjectDatabaseUsers:getCloudProjectDatabaseUsers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudProjectDatabaseUsers.
type GetCloudProjectDatabaseUsersArgs struct {
	// Cluster ID
	ClusterId string `pulumi:"clusterId"`
	// The engine of the database cluster you want to list users. To get a full list of available engine visit.
	// [public documentation](https://docs.ovh.com/gb/en/publiccloud/databases).
	Engine string `pulumi:"engine"`
	// The id of the public cloud project. If omitted,
	// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName string `pulumi:"serviceName"`
}

// A collection of values returned by getCloudProjectDatabaseUsers.
type GetCloudProjectDatabaseUsersResult struct {
	ClusterId string `pulumi:"clusterId"`
	Engine    string `pulumi:"engine"`
	// The provider-assigned unique ID for this managed resource.
	Id          string `pulumi:"id"`
	ServiceName string `pulumi:"serviceName"`
	// The list of users ids of the database cluster associated with the project.
	UserIds []string `pulumi:"userIds"`
}

func GetCloudProjectDatabaseUsersOutput(ctx *pulumi.Context, args GetCloudProjectDatabaseUsersOutputArgs, opts ...pulumi.InvokeOption) GetCloudProjectDatabaseUsersResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCloudProjectDatabaseUsersResult, error) {
			args := v.(GetCloudProjectDatabaseUsersArgs)
			r, err := GetCloudProjectDatabaseUsers(ctx, &args, opts...)
			var s GetCloudProjectDatabaseUsersResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetCloudProjectDatabaseUsersResultOutput)
}

// A collection of arguments for invoking getCloudProjectDatabaseUsers.
type GetCloudProjectDatabaseUsersOutputArgs struct {
	// Cluster ID
	ClusterId pulumi.StringInput `pulumi:"clusterId"`
	// The engine of the database cluster you want to list users. To get a full list of available engine visit.
	// [public documentation](https://docs.ovh.com/gb/en/publiccloud/databases).
	Engine pulumi.StringInput `pulumi:"engine"`
	// The id of the public cloud project. If omitted,
	// the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
	ServiceName pulumi.StringInput `pulumi:"serviceName"`
}

func (GetCloudProjectDatabaseUsersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseUsersArgs)(nil)).Elem()
}

// A collection of values returned by getCloudProjectDatabaseUsers.
type GetCloudProjectDatabaseUsersResultOutput struct{ *pulumi.OutputState }

func (GetCloudProjectDatabaseUsersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCloudProjectDatabaseUsersResult)(nil)).Elem()
}

func (o GetCloudProjectDatabaseUsersResultOutput) ToGetCloudProjectDatabaseUsersResultOutput() GetCloudProjectDatabaseUsersResultOutput {
	return o
}

func (o GetCloudProjectDatabaseUsersResultOutput) ToGetCloudProjectDatabaseUsersResultOutputWithContext(ctx context.Context) GetCloudProjectDatabaseUsersResultOutput {
	return o
}

func (o GetCloudProjectDatabaseUsersResultOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseUsersResult) string { return v.ClusterId }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseUsersResultOutput) Engine() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseUsersResult) string { return v.Engine }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetCloudProjectDatabaseUsersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseUsersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCloudProjectDatabaseUsersResultOutput) ServiceName() pulumi.StringOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseUsersResult) string { return v.ServiceName }).(pulumi.StringOutput)
}

// The list of users ids of the database cluster associated with the project.
func (o GetCloudProjectDatabaseUsersResultOutput) UserIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetCloudProjectDatabaseUsersResult) []string { return v.UserIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCloudProjectDatabaseUsersResultOutput{})
}
