// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ovh

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates an IPXE Script.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"fmt"
//	"io/ioutil"
//
//	"github.com/lbrlabs/pulumi-ovh/sdk/go/ovh"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func readFileOrPanic(path string) pulumi.StringPtrInput {
//		data, err := ioutil.ReadFile(path)
//		if err != nil {
//			panic(err.Error())
//		}
//		return pulumi.String(string(data))
//	}
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := ovh.NewMeIpxeScript(ctx, "script", &ovh.MeIpxeScriptArgs{
//				Script: readFileOrPanic(fmt.Sprintf("%v/boot.ipxe", path.Module)),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type MeIpxeScript struct {
	pulumi.CustomResourceState

	// For documentation purpose only. This attribute is not passed to the OVH API as it cannot be retrieved back. Instead a fake description ('$name auto description') is passed at creation time.
	Description pulumi.StringOutput `pulumi:"description"`
	// The name of the IPXE Script.
	Name pulumi.StringOutput `pulumi:"name"`
	// The content of the script.
	Script pulumi.StringOutput `pulumi:"script"`
}

// NewMeIpxeScript registers a new resource with the given unique name, arguments, and options.
func NewMeIpxeScript(ctx *pulumi.Context,
	name string, args *MeIpxeScriptArgs, opts ...pulumi.ResourceOption) (*MeIpxeScript, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Script == nil {
		return nil, errors.New("invalid value for required argument 'Script'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource MeIpxeScript
	err := ctx.RegisterResource("ovh:index/meIpxeScript:MeIpxeScript", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMeIpxeScript gets an existing MeIpxeScript resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMeIpxeScript(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MeIpxeScriptState, opts ...pulumi.ResourceOption) (*MeIpxeScript, error) {
	var resource MeIpxeScript
	err := ctx.ReadResource("ovh:index/meIpxeScript:MeIpxeScript", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MeIpxeScript resources.
type meIpxeScriptState struct {
	// For documentation purpose only. This attribute is not passed to the OVH API as it cannot be retrieved back. Instead a fake description ('$name auto description') is passed at creation time.
	Description *string `pulumi:"description"`
	// The name of the IPXE Script.
	Name *string `pulumi:"name"`
	// The content of the script.
	Script *string `pulumi:"script"`
}

type MeIpxeScriptState struct {
	// For documentation purpose only. This attribute is not passed to the OVH API as it cannot be retrieved back. Instead a fake description ('$name auto description') is passed at creation time.
	Description pulumi.StringPtrInput
	// The name of the IPXE Script.
	Name pulumi.StringPtrInput
	// The content of the script.
	Script pulumi.StringPtrInput
}

func (MeIpxeScriptState) ElementType() reflect.Type {
	return reflect.TypeOf((*meIpxeScriptState)(nil)).Elem()
}

type meIpxeScriptArgs struct {
	// For documentation purpose only. This attribute is not passed to the OVH API as it cannot be retrieved back. Instead a fake description ('$name auto description') is passed at creation time.
	Description *string `pulumi:"description"`
	// The name of the IPXE Script.
	Name *string `pulumi:"name"`
	// The content of the script.
	Script string `pulumi:"script"`
}

// The set of arguments for constructing a MeIpxeScript resource.
type MeIpxeScriptArgs struct {
	// For documentation purpose only. This attribute is not passed to the OVH API as it cannot be retrieved back. Instead a fake description ('$name auto description') is passed at creation time.
	Description pulumi.StringPtrInput
	// The name of the IPXE Script.
	Name pulumi.StringPtrInput
	// The content of the script.
	Script pulumi.StringInput
}

func (MeIpxeScriptArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*meIpxeScriptArgs)(nil)).Elem()
}

type MeIpxeScriptInput interface {
	pulumi.Input

	ToMeIpxeScriptOutput() MeIpxeScriptOutput
	ToMeIpxeScriptOutputWithContext(ctx context.Context) MeIpxeScriptOutput
}

func (*MeIpxeScript) ElementType() reflect.Type {
	return reflect.TypeOf((**MeIpxeScript)(nil)).Elem()
}

func (i *MeIpxeScript) ToMeIpxeScriptOutput() MeIpxeScriptOutput {
	return i.ToMeIpxeScriptOutputWithContext(context.Background())
}

func (i *MeIpxeScript) ToMeIpxeScriptOutputWithContext(ctx context.Context) MeIpxeScriptOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MeIpxeScriptOutput)
}

// MeIpxeScriptArrayInput is an input type that accepts MeIpxeScriptArray and MeIpxeScriptArrayOutput values.
// You can construct a concrete instance of `MeIpxeScriptArrayInput` via:
//
//	MeIpxeScriptArray{ MeIpxeScriptArgs{...} }
type MeIpxeScriptArrayInput interface {
	pulumi.Input

	ToMeIpxeScriptArrayOutput() MeIpxeScriptArrayOutput
	ToMeIpxeScriptArrayOutputWithContext(context.Context) MeIpxeScriptArrayOutput
}

type MeIpxeScriptArray []MeIpxeScriptInput

func (MeIpxeScriptArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MeIpxeScript)(nil)).Elem()
}

func (i MeIpxeScriptArray) ToMeIpxeScriptArrayOutput() MeIpxeScriptArrayOutput {
	return i.ToMeIpxeScriptArrayOutputWithContext(context.Background())
}

func (i MeIpxeScriptArray) ToMeIpxeScriptArrayOutputWithContext(ctx context.Context) MeIpxeScriptArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MeIpxeScriptArrayOutput)
}

// MeIpxeScriptMapInput is an input type that accepts MeIpxeScriptMap and MeIpxeScriptMapOutput values.
// You can construct a concrete instance of `MeIpxeScriptMapInput` via:
//
//	MeIpxeScriptMap{ "key": MeIpxeScriptArgs{...} }
type MeIpxeScriptMapInput interface {
	pulumi.Input

	ToMeIpxeScriptMapOutput() MeIpxeScriptMapOutput
	ToMeIpxeScriptMapOutputWithContext(context.Context) MeIpxeScriptMapOutput
}

type MeIpxeScriptMap map[string]MeIpxeScriptInput

func (MeIpxeScriptMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MeIpxeScript)(nil)).Elem()
}

func (i MeIpxeScriptMap) ToMeIpxeScriptMapOutput() MeIpxeScriptMapOutput {
	return i.ToMeIpxeScriptMapOutputWithContext(context.Background())
}

func (i MeIpxeScriptMap) ToMeIpxeScriptMapOutputWithContext(ctx context.Context) MeIpxeScriptMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MeIpxeScriptMapOutput)
}

type MeIpxeScriptOutput struct{ *pulumi.OutputState }

func (MeIpxeScriptOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MeIpxeScript)(nil)).Elem()
}

func (o MeIpxeScriptOutput) ToMeIpxeScriptOutput() MeIpxeScriptOutput {
	return o
}

func (o MeIpxeScriptOutput) ToMeIpxeScriptOutputWithContext(ctx context.Context) MeIpxeScriptOutput {
	return o
}

// For documentation purpose only. This attribute is not passed to the OVH API as it cannot be retrieved back. Instead a fake description ('$name auto description') is passed at creation time.
func (o MeIpxeScriptOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *MeIpxeScript) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// The name of the IPXE Script.
func (o MeIpxeScriptOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MeIpxeScript) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The content of the script.
func (o MeIpxeScriptOutput) Script() pulumi.StringOutput {
	return o.ApplyT(func(v *MeIpxeScript) pulumi.StringOutput { return v.Script }).(pulumi.StringOutput)
}

type MeIpxeScriptArrayOutput struct{ *pulumi.OutputState }

func (MeIpxeScriptArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MeIpxeScript)(nil)).Elem()
}

func (o MeIpxeScriptArrayOutput) ToMeIpxeScriptArrayOutput() MeIpxeScriptArrayOutput {
	return o
}

func (o MeIpxeScriptArrayOutput) ToMeIpxeScriptArrayOutputWithContext(ctx context.Context) MeIpxeScriptArrayOutput {
	return o
}

func (o MeIpxeScriptArrayOutput) Index(i pulumi.IntInput) MeIpxeScriptOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MeIpxeScript {
		return vs[0].([]*MeIpxeScript)[vs[1].(int)]
	}).(MeIpxeScriptOutput)
}

type MeIpxeScriptMapOutput struct{ *pulumi.OutputState }

func (MeIpxeScriptMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MeIpxeScript)(nil)).Elem()
}

func (o MeIpxeScriptMapOutput) ToMeIpxeScriptMapOutput() MeIpxeScriptMapOutput {
	return o
}

func (o MeIpxeScriptMapOutput) ToMeIpxeScriptMapOutputWithContext(ctx context.Context) MeIpxeScriptMapOutput {
	return o
}

func (o MeIpxeScriptMapOutput) MapIndex(k pulumi.StringInput) MeIpxeScriptOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MeIpxeScript {
		return vs[0].(map[string]*MeIpxeScript)[vs[1].(string)]
	}).(MeIpxeScriptOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MeIpxeScriptInput)(nil)).Elem(), &MeIpxeScript{})
	pulumi.RegisterInputType(reflect.TypeOf((*MeIpxeScriptArrayInput)(nil)).Elem(), MeIpxeScriptArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MeIpxeScriptMapInput)(nil)).Elem(), MeIpxeScriptMap{})
	pulumi.RegisterOutputType(MeIpxeScriptOutput{})
	pulumi.RegisterOutputType(MeIpxeScriptArrayOutput{})
	pulumi.RegisterOutputType(MeIpxeScriptMapOutput{})
}
