// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dbaas

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-ovh/sdk/go/ovh/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about an identity group.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/lbrlabs/pulumi-ovh/sdk/go/ovh/Dbaas"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := Dbaas.GetMeIdentityGroup(ctx, &dbaas.GetMeIdentityGroupArgs{
//				Name: "my_group_name",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupMeIdentityGroup(ctx *pulumi.Context, args *LookupMeIdentityGroupArgs, opts ...pulumi.InvokeOption) (*LookupMeIdentityGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupMeIdentityGroupResult
	err := ctx.Invoke("ovh:Dbaas/getMeIdentityGroup:getMeIdentityGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMeIdentityGroup.
type LookupMeIdentityGroupArgs struct {
	// Group name.
	Name string `pulumi:"name"`
}

// A collection of values returned by getMeIdentityGroup.
type LookupMeIdentityGroupResult struct {
	// Creation date of this group.
	Creation string `pulumi:"creation"`
	// Is the group a default and immutable one.
	DefaultGroup bool `pulumi:"defaultGroup"`
	// Group description.
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Date of the last update of this group.
	LastUpdate string `pulumi:"lastUpdate"`
	Name       string `pulumi:"name"`
	// Role associated with the group. Valid roles are ADMIN, REGULAR, UNPRIVILEGED, and NONE.
	Role string `pulumi:"role"`
}

func LookupMeIdentityGroupOutput(ctx *pulumi.Context, args LookupMeIdentityGroupOutputArgs, opts ...pulumi.InvokeOption) LookupMeIdentityGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupMeIdentityGroupResult, error) {
			args := v.(LookupMeIdentityGroupArgs)
			r, err := LookupMeIdentityGroup(ctx, &args, opts...)
			var s LookupMeIdentityGroupResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupMeIdentityGroupResultOutput)
}

// A collection of arguments for invoking getMeIdentityGroup.
type LookupMeIdentityGroupOutputArgs struct {
	// Group name.
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupMeIdentityGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMeIdentityGroupArgs)(nil)).Elem()
}

// A collection of values returned by getMeIdentityGroup.
type LookupMeIdentityGroupResultOutput struct{ *pulumi.OutputState }

func (LookupMeIdentityGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupMeIdentityGroupResult)(nil)).Elem()
}

func (o LookupMeIdentityGroupResultOutput) ToLookupMeIdentityGroupResultOutput() LookupMeIdentityGroupResultOutput {
	return o
}

func (o LookupMeIdentityGroupResultOutput) ToLookupMeIdentityGroupResultOutputWithContext(ctx context.Context) LookupMeIdentityGroupResultOutput {
	return o
}

// Creation date of this group.
func (o LookupMeIdentityGroupResultOutput) Creation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityGroupResult) string { return v.Creation }).(pulumi.StringOutput)
}

// Is the group a default and immutable one.
func (o LookupMeIdentityGroupResultOutput) DefaultGroup() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupMeIdentityGroupResult) bool { return v.DefaultGroup }).(pulumi.BoolOutput)
}

// Group description.
func (o LookupMeIdentityGroupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityGroupResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupMeIdentityGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

// Date of the last update of this group.
func (o LookupMeIdentityGroupResultOutput) LastUpdate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityGroupResult) string { return v.LastUpdate }).(pulumi.StringOutput)
}

func (o LookupMeIdentityGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

// Role associated with the group. Valid roles are ADMIN, REGULAR, UNPRIVILEGED, and NONE.
func (o LookupMeIdentityGroupResultOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v LookupMeIdentityGroupResult) string { return v.Role }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupMeIdentityGroupResultOutput{})
}
