// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class DbaasLogsInputConfigurationFlowggerArgs extends com.pulumi.resources.ResourceArgs {

    public static final DbaasLogsInputConfigurationFlowggerArgs Empty = new DbaasLogsInputConfigurationFlowggerArgs();

    /**
     * Type of format to decode. One of &#34;RFC5424&#34;, &#34;LTSV&#34;, &#34;GELF&#34;, &#34;CAPNP&#34;
     * 
     */
    @Import(name="logFormat", required=true)
    private Output<String> logFormat;

    /**
     * @return Type of format to decode. One of &#34;RFC5424&#34;, &#34;LTSV&#34;, &#34;GELF&#34;, &#34;CAPNP&#34;
     * 
     */
    public Output<String> logFormat() {
        return this.logFormat;
    }

    /**
     * Indicates how messages are delimited. One of &#34;LINE&#34;, &#34;NUL&#34;, &#34;SYSLEN&#34;, &#34;CAPNP&#34;
     * 
     */
    @Import(name="logFraming", required=true)
    private Output<String> logFraming;

    /**
     * @return Indicates how messages are delimited. One of &#34;LINE&#34;, &#34;NUL&#34;, &#34;SYSLEN&#34;, &#34;CAPNP&#34;
     * 
     */
    public Output<String> logFraming() {
        return this.logFraming;
    }

    private DbaasLogsInputConfigurationFlowggerArgs() {}

    private DbaasLogsInputConfigurationFlowggerArgs(DbaasLogsInputConfigurationFlowggerArgs $) {
        this.logFormat = $.logFormat;
        this.logFraming = $.logFraming;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DbaasLogsInputConfigurationFlowggerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DbaasLogsInputConfigurationFlowggerArgs $;

        public Builder() {
            $ = new DbaasLogsInputConfigurationFlowggerArgs();
        }

        public Builder(DbaasLogsInputConfigurationFlowggerArgs defaults) {
            $ = new DbaasLogsInputConfigurationFlowggerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param logFormat Type of format to decode. One of &#34;RFC5424&#34;, &#34;LTSV&#34;, &#34;GELF&#34;, &#34;CAPNP&#34;
         * 
         * @return builder
         * 
         */
        public Builder logFormat(Output<String> logFormat) {
            $.logFormat = logFormat;
            return this;
        }

        /**
         * @param logFormat Type of format to decode. One of &#34;RFC5424&#34;, &#34;LTSV&#34;, &#34;GELF&#34;, &#34;CAPNP&#34;
         * 
         * @return builder
         * 
         */
        public Builder logFormat(String logFormat) {
            return logFormat(Output.of(logFormat));
        }

        /**
         * @param logFraming Indicates how messages are delimited. One of &#34;LINE&#34;, &#34;NUL&#34;, &#34;SYSLEN&#34;, &#34;CAPNP&#34;
         * 
         * @return builder
         * 
         */
        public Builder logFraming(Output<String> logFraming) {
            $.logFraming = logFraming;
            return this;
        }

        /**
         * @param logFraming Indicates how messages are delimited. One of &#34;LINE&#34;, &#34;NUL&#34;, &#34;SYSLEN&#34;, &#34;CAPNP&#34;
         * 
         * @return builder
         * 
         */
        public Builder logFraming(String logFraming) {
            return logFraming(Output.of(logFraming));
        }

        public DbaasLogsInputConfigurationFlowggerArgs build() {
            $.logFormat = Objects.requireNonNull($.logFormat, "expected parameter 'logFormat' to be non-null");
            $.logFraming = Objects.requireNonNull($.logFraming, "expected parameter 'logFraming' to be non-null");
            return $;
        }
    }

}
