// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetCloudProjectCapabilitiesContainerFilterArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudProjectCapabilitiesContainerFilterArgs Empty = new GetCloudProjectCapabilitiesContainerFilterArgs();

    /**
     * The plan name
     * 
     */
    @Import(name="planName", required=true)
    private Output<String> planName;

    /**
     * @return The plan name
     * 
     */
    public Output<String> planName() {
        return this.planName;
    }

    /**
     * The region name
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return The region name
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    /**
     * The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     * 
     */
    @Import(name="serviceName", required=true)
    private Output<String> serviceName;

    /**
     * @return The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     * 
     */
    public Output<String> serviceName() {
        return this.serviceName;
    }

    private GetCloudProjectCapabilitiesContainerFilterArgs() {}

    private GetCloudProjectCapabilitiesContainerFilterArgs(GetCloudProjectCapabilitiesContainerFilterArgs $) {
        this.planName = $.planName;
        this.region = $.region;
        this.serviceName = $.serviceName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudProjectCapabilitiesContainerFilterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudProjectCapabilitiesContainerFilterArgs $;

        public Builder() {
            $ = new GetCloudProjectCapabilitiesContainerFilterArgs();
        }

        public Builder(GetCloudProjectCapabilitiesContainerFilterArgs defaults) {
            $ = new GetCloudProjectCapabilitiesContainerFilterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param planName The plan name
         * 
         * @return builder
         * 
         */
        public Builder planName(Output<String> planName) {
            $.planName = planName;
            return this;
        }

        /**
         * @param planName The plan name
         * 
         * @return builder
         * 
         */
        public Builder planName(String planName) {
            return planName(Output.of(planName));
        }

        /**
         * @param region The region name
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region The region name
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param serviceName The id of the public cloud project. If omitted,
         * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(Output<String> serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        /**
         * @param serviceName The id of the public cloud project. If omitted,
         * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            return serviceName(Output.of(serviceName));
        }

        public GetCloudProjectCapabilitiesContainerFilterArgs build() {
            $.planName = Objects.requireNonNull($.planName, "expected parameter 'planName' to be non-null");
            $.region = Objects.requireNonNull($.region, "expected parameter 'region' to be non-null");
            $.serviceName = Objects.requireNonNull($.serviceName, "expected parameter 'serviceName' to be non-null");
            return $;
        }
    }

}
