// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ovh.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class GetCloudProjectCapabilitiesContainerFilterPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudProjectCapabilitiesContainerFilterPlainArgs Empty = new GetCloudProjectCapabilitiesContainerFilterPlainArgs();

    /**
     * The plan name
     * 
     */
    @Import(name="planName", required=true)
    private String planName;

    /**
     * @return The plan name
     * 
     */
    public String planName() {
        return this.planName;
    }

    /**
     * The region name
     * 
     */
    @Import(name="region", required=true)
    private String region;

    /**
     * @return The region name
     * 
     */
    public String region() {
        return this.region;
    }

    /**
     * The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     * 
     */
    @Import(name="serviceName", required=true)
    private String serviceName;

    /**
     * @return The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     * 
     */
    public String serviceName() {
        return this.serviceName;
    }

    private GetCloudProjectCapabilitiesContainerFilterPlainArgs() {}

    private GetCloudProjectCapabilitiesContainerFilterPlainArgs(GetCloudProjectCapabilitiesContainerFilterPlainArgs $) {
        this.planName = $.planName;
        this.region = $.region;
        this.serviceName = $.serviceName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudProjectCapabilitiesContainerFilterPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudProjectCapabilitiesContainerFilterPlainArgs $;

        public Builder() {
            $ = new GetCloudProjectCapabilitiesContainerFilterPlainArgs();
        }

        public Builder(GetCloudProjectCapabilitiesContainerFilterPlainArgs defaults) {
            $ = new GetCloudProjectCapabilitiesContainerFilterPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param planName The plan name
         * 
         * @return builder
         * 
         */
        public Builder planName(String planName) {
            $.planName = planName;
            return this;
        }

        /**
         * @param region The region name
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            $.region = region;
            return this;
        }

        /**
         * @param serviceName The id of the public cloud project. If omitted,
         * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
         * 
         * @return builder
         * 
         */
        public Builder serviceName(String serviceName) {
            $.serviceName = serviceName;
            return this;
        }

        public GetCloudProjectCapabilitiesContainerFilterPlainArgs build() {
            $.planName = Objects.requireNonNull($.planName, "expected parameter 'planName' to be non-null");
            $.region = Objects.requireNonNull($.region, "expected parameter 'region' to be non-null");
            $.serviceName = Objects.requireNonNull($.serviceName, "expected parameter 'serviceName' to be non-null");
            return $;
        }
    }

}
