name: main

permissions:
  contents: write


"on":
  push:
    branches:
    - main
    paths-ignore:
    - CHANGELOG.md
    tags-ignore:
    - v*
    - sdk/*
    - '**'

jobs:
  main:
    uses: jaxxstorm/workflows/.github/workflows/main.yml@df55f0116159ea8d30f836557f05a3c699a37a63
    with:
      pulumi_test_owner: "lbrlabs"
      provider_name: "ovh"

