name: main

"on":
  push:
    branches:
    - main
    paths-ignore:
    - CHANGELOG.md
    tags-ignore:
    - v*
    - sdk/*
    - '**'

jobs:
  main:
    uses: jaxxstorm/workflows/.github/workflows/main.yml@fe98a0730026bf97b10e11bd96b3d38425031bd1
    with:
      pulumi_test_owner: "lbrlabs"
      provider_name: "ovh"

