// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Use this data source to filter the list of container registry capabilities associated with a public cloud project to match one and only one capability.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const capability = pulumi.output(ovh.getCloudProjectCapabilitiesContainerFilter({
 *     planName: "SMALL",
 *     region: "GRA",
 *     serviceName: "XXXXXX",
 * }));
 * ```
 */
export function getCloudProjectCapabilitiesContainerFilter(args: GetCloudProjectCapabilitiesContainerFilterArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudProjectCapabilitiesContainerFilterResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ovh:index/getCloudProjectCapabilitiesContainerFilter:getCloudProjectCapabilitiesContainerFilter", {
        "planName": args.planName,
        "region": args.region,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudProjectCapabilitiesContainerFilter.
 */
export interface GetCloudProjectCapabilitiesContainerFilterArgs {
    /**
     * The plan name
     */
    planName: string;
    /**
     * The region name
     */
    region: string;
    /**
     * The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     */
    serviceName: string;
}

/**
 * A collection of values returned by getCloudProjectCapabilitiesContainerFilter.
 */
export interface GetCloudProjectCapabilitiesContainerFilterResult {
    /**
     * Plan code from the catalog
     */
    readonly code: string;
    /**
     * Plan creation date
     */
    readonly createdAt: string;
    /**
     * Features of the plan
     */
    readonly features: outputs.GetCloudProjectCapabilitiesContainerFilterFeature[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Plan name
     */
    readonly name: string;
    readonly planName: string;
    readonly region: string;
    /**
     * Container registry limits
     */
    readonly registryLimits: outputs.GetCloudProjectCapabilitiesContainerFilterRegistryLimit[];
    readonly serviceName: string;
    /**
     * Plan last update date
     */
    readonly updatedAt: string;
}

export function getCloudProjectCapabilitiesContainerFilterOutput(args: GetCloudProjectCapabilitiesContainerFilterOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCloudProjectCapabilitiesContainerFilterResult> {
    return pulumi.output(args).apply(a => getCloudProjectCapabilitiesContainerFilter(a, opts))
}

/**
 * A collection of arguments for invoking getCloudProjectCapabilitiesContainerFilter.
 */
export interface GetCloudProjectCapabilitiesContainerFilterOutputArgs {
    /**
     * The plan name
     */
    planName: pulumi.Input<string>;
    /**
     * The region name
     */
    region: pulumi.Input<string>;
    /**
     * The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     */
    serviceName: pulumi.Input<string>;
}
