// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to get the details of a failover ip address of a service in a public cloud project.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const myfailoverip = pulumi.output(ovh.getCloudProjectFailoverIpAttach({
 *     ip: "XXXXXX",
 *     serviceName: "XXXXXX",
 * }));
 * ```
 */
export function getCloudProjectFailoverIpAttach(args: GetCloudProjectFailoverIpAttachArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudProjectFailoverIpAttachResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ovh:index/getCloudProjectFailoverIpAttach:getCloudProjectFailoverIpAttach", {
        "block": args.block,
        "continentCode": args.continentCode,
        "geoLoc": args.geoLoc,
        "ip": args.ip,
        "routedTo": args.routedTo,
        "serviceName": args.serviceName,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudProjectFailoverIpAttach.
 */
export interface GetCloudProjectFailoverIpAttachArgs {
    /**
     * The IP block
     */
    block?: string;
    continentCode?: string;
    geoLoc?: string;
    /**
     * The failover ip address to query
     */
    ip?: string;
    routedTo?: string;
    /**
     * The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     */
    serviceName: string;
}

/**
 * A collection of values returned by getCloudProjectFailoverIpAttach.
 */
export interface GetCloudProjectFailoverIpAttachResult {
    /**
     * The IP block
     */
    readonly block: string;
    readonly continentCode: string;
    readonly geoLoc: string;
    /**
     * The Ip id
     */
    readonly id: string;
    /**
     * The Ip Address
     */
    readonly ip: string;
    /**
     * Current operation progress in percent
     */
    readonly progress: number;
    readonly routedTo: string;
    readonly serviceName: string;
    /**
     * Ip status, can be `ok` or `operationPending`
     */
    readonly status: string;
    readonly subType: string;
}

export function getCloudProjectFailoverIpAttachOutput(args: GetCloudProjectFailoverIpAttachOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCloudProjectFailoverIpAttachResult> {
    return pulumi.output(args).apply(a => getCloudProjectFailoverIpAttach(a, opts))
}

/**
 * A collection of arguments for invoking getCloudProjectFailoverIpAttach.
 */
export interface GetCloudProjectFailoverIpAttachOutputArgs {
    /**
     * The IP block
     */
    block?: pulumi.Input<string>;
    continentCode?: pulumi.Input<string>;
    geoLoc?: pulumi.Input<string>;
    /**
     * The failover ip address to query
     */
    ip?: pulumi.Input<string>;
    routedTo?: pulumi.Input<string>;
    /**
     * The id of the public cloud project. If omitted,
     * the `OVH_CLOUD_PROJECT_SERVICE` environment variable is used.
     */
    serviceName: pulumi.Input<string>;
}
