// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information of order cart product plan.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ovh from "@pulumi/ovh";
 *
 * const mycart = ovh.getOrderCart({
 *     ovhSubsidiary: "fr",
 *     description: "my cart",
 * });
 * const plan = mycart.then(mycart => ovh.getOrderCartProductPlan({
 *     cartId: mycart.id,
 *     priceCapacity: "renew",
 *     product: "cloud",
 *     planCode: "project",
 * }));
 * ```
 */
export function getOrderCartProductPlan(args: GetOrderCartProductPlanArgs, opts?: pulumi.InvokeOptions): Promise<GetOrderCartProductPlanResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("ovh:index/getOrderCartProductPlan:getOrderCartProductPlan", {
        "cartId": args.cartId,
        "catalogName": args.catalogName,
        "planCode": args.planCode,
        "priceCapacity": args.priceCapacity,
        "product": args.product,
    }, opts);
}

/**
 * A collection of arguments for invoking getOrderCartProductPlan.
 */
export interface GetOrderCartProductPlanArgs {
    /**
     * Cart identifier
     */
    cartId: string;
    /**
     * Catalog name
     */
    catalogName?: string;
    /**
     * Product offer identifier
     */
    planCode: string;
    /**
     * Capacity of the pricing (type of pricing)
     */
    priceCapacity: string;
    /**
     * Product
     */
    product: string;
}

/**
 * A collection of values returned by getOrderCartProductPlan.
 */
export interface GetOrderCartProductPlanResult {
    readonly cartId: string;
    readonly catalogName?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Product offer identifier
     */
    readonly planCode: string;
    readonly priceCapacity: string;
    /**
     * Prices of the product offer
     */
    readonly prices: outputs.GetOrderCartProductPlanPrice[];
    readonly product: string;
    /**
     * Name of the product
     */
    readonly productName: string;
    /**
     * Product type
     */
    readonly productType: string;
    /**
     * Selected Price according to capacity
     */
    readonly selectedPrices: outputs.GetOrderCartProductPlanSelectedPrice[];
}

export function getOrderCartProductPlanOutput(args: GetOrderCartProductPlanOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetOrderCartProductPlanResult> {
    return pulumi.output(args).apply(a => getOrderCartProductPlan(a, opts))
}

/**
 * A collection of arguments for invoking getOrderCartProductPlan.
 */
export interface GetOrderCartProductPlanOutputArgs {
    /**
     * Cart identifier
     */
    cartId: pulumi.Input<string>;
    /**
     * Catalog name
     */
    catalogName?: pulumi.Input<string>;
    /**
     * Product offer identifier
     */
    planCode: pulumi.Input<string>;
    /**
     * Capacity of the pricing (type of pricing)
     */
    priceCapacity: pulumi.Input<string>;
    /**
     * Product
     */
    product: pulumi.Input<string>;
}
